### ISSUE TITLE
Testinfra doesn't appear to respect StrictHostKeyChecking with ansible connection

### ISSUE THREAD

**Issue by retr0h** [philpep/testinfra#203]
I am using the ansible connection.  I am not relying on any ssh configuration in ansible.cfg.  Everything is configured via `ansible_ssh_extra_args` magic variable.

```
$ testinfra --version
This is pytest version 3.0.7, imported from /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule2-env-2.7.13/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  testinfra-1.6.2 at /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule2-env-2.7.13/lib/python2.7/site-packages/testinfra/plugin.py
  pytest-verbose-parametrize-1.2.2 at /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule2-env-2.7.13/lib/python2.7/site-packages/pytest_verbose_parametrize.py
  pytest-mock-1.6.0 at /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule2-env-2.7.13/lib/python2.7/site-packages/pytest_mock.py
  pytest-helpers-namespace-2016.7.10 at /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule2-env-2.7.13/lib/python2.7/site-packages/pytest_helpers_namespace/plugin.py
  pytest-cov-2.4.0 at /Users/jodewey/.pyenv/versions/2.7.13/envs/molecule2-env-2.7.13/lib/python2.7/site-packages/pytest_cov/plugin.py
```

```
$ ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May  4 2017, 15:45:50) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

My ansible inventory:

```yaml
$ cat molecule/default/.molecule/ansible_inventory.yml
# Molecule managed

---
all:
  hosts:
    instance-1-default: &id001
      ansible_host: ec2-52-14-173-9.us-east-2.compute.amazonaws.com
      ansible_port: 22
      ansible_private_key_file: /Users/jodewey/git/molecule_2/test/scenarios/driver/ec2/molecule/default/.molecule/ssh_key
      ansible_scp_extra_args: -o ControlPath=~/.ansible/cp/%C
      ansible_ssh_extra_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o
        ControlPath=~/.ansible/cp/%C
      ansible_user: ubuntu
      connection: ssh
ungrouped:
  hosts:
    instance-1-default: *id001
  vars: {}
```

Error:

```
    ----------------------------- Captured stderr call -----------------------------
     [WARNING]: Failure using method (v2_runner_on_unreachable) in callback plugin
    (<testinfra.utils.ansible_runner.Callback object at 0x1054d4a10>): Host
    instance-1-default is unreachable: {'changed': False,  'msg': u'Failed to
    connect to the host via ssh: Host key verification failed.\r\nConnection
    closed\r\n',  'unreachable': True}
    ============================ pytest-warning summary ============================
    WP1 None Module already imported so can not be re-written: testinfra
    ============ 2 failed, 1 passed, 1 pytest-warnings in 2.81 seconds =============
```

However, ansible converges perfectly fine on it's own.  Which uses the inventory stated above.

```
$ molecule converge
--> Scenario: [default]
--> Provisioner: [ansible]
--> Driver: [ec2]
--> Playbook: [create.yml]
Skipping, instances already created.
--> Scenario: [default]
--> Provisioner: [ansible]
--> Playbook: [playbook.yml]

    PLAY [all] *********************************************************************

    TASK [Install python for Ansible] **********************************************
    ok: [instance-1-default]

    PLAY [all] *********************************************************************

    TASK [Gathering Facts] *********************************************************
    ok: [instance-1-default]

    TASK [molecule : Create /etc/molecule] *****************************************
    ok: [instance-1-default]

    TASK [molecule : Create /etc/molecule/ip-172-31-26-82] *************************
    ok: [instance-1-default]

    PLAY RECAP *********************************************************************
    instance-1-default         : ok=4    changed=0    unreachable=0    failed=0

```

The testinfra command being run:

```
$ testinfra --debug --connection=ansible --ansible-inventory=/Users/jodewey/git/molecule_2/test/scenarios/driver/ec2/molecule/default/.molecule/ansible_inventory.yml /Users/jodewey/git/molecule_2/test/scenarios/driver/ec2/molecule/default/tests/test_default.py
```
