### ISSUE TITLE
Not working with molecule - name + port used for Docker

### ISSUE THREAD

**Issue by hypery2k** [philpep/testinfra#465]
With the latest testinfra version during a molecule setup, it seems that the port is used for picking up the container:

```
No such container: instance:7525\
```

But the port should be dropped, as the name is "instance" only (molecule.yml):

```
platforms:
  - name: instance
    image: debian
    image_version: 9
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 22/tcp
      - 7525/tcp
    groups:
      - debian
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: ../../ansible/internal.yml
  inventory:
    group_vars:
      all:
        ansible_port: 7525
        modern_tls: false
        additional_admins: []
        ansible_become: false
        ansible_user: root
```

Any ideas?
